//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder v2.1.3.52
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Zbu.ModelsBuilder;
using Zbu.ModelsBuilder.Umbraco;

namespace V8Media.Framework.Models.PublishedContent
{
	/// <summary>Website</summary>
	[PublishedContentModel("Website")]
	public partial class Website : Data
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Website";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Website(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Website, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		/// <summary>Address Line 1</summary>
		[ImplementPropertyType("addressLine1")]
		public string AddressLine1
		{
			get { return this.GetPropertyValue<string>("addressLine1"); }
		}

		/// <summary>Address Line 2</summary>
		[ImplementPropertyType("addressLine2")]
		public string AddressLine2
		{
			get { return this.GetPropertyValue<string>("addressLine2"); }
		}

		/// <summary>Behance</summary>
		[ImplementPropertyType("behance")]
		public string Behance
		{
			get { return this.GetPropertyValue<string>("behance"); }
		}

		/// <summary>Blog</summary>
		[ImplementPropertyType("blog")]
		public string Blog
		{
			get { return this.GetPropertyValue<string>("blog"); }
		}

		/// <summary>City</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		/// <summary>Company Name</summary>
		[ImplementPropertyType("companyName")]
		public string CompanyName
		{
			get { return this.GetPropertyValue<string>("companyName"); }
		}

		/// <summary>County</summary>
		[ImplementPropertyType("county")]
		public string County
		{
			get { return this.GetPropertyValue<string>("county"); }
		}

		/// <summary>Dribble</summary>
		[ImplementPropertyType("dribble")]
		public string Dribble
		{
			get { return this.GetPropertyValue<string>("dribble"); }
		}

		/// <summary>Email</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		/// <summary>Facebook</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		/// <summary>Fax</summary>
		[ImplementPropertyType("fax")]
		public string Fax
		{
			get { return this.GetPropertyValue<string>("fax"); }
		}

		/// <summary>Flickr</summary>
		[ImplementPropertyType("flickr")]
		public string Flickr
		{
			get { return this.GetPropertyValue<string>("flickr"); }
		}

		/// <summary>Google+</summary>
		[ImplementPropertyType("googleplus")]
		public string Googleplus
		{
			get { return this.GetPropertyValue<string>("googleplus"); }
		}

		/// <summary>Instagram</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return this.GetPropertyValue<string>("instagram"); }
		}

		/// <summary>URL Redirect</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public IPublishedContent InternalUrlRedirect
		{
			get { return this.GetPropertyValue<IPublishedContent>("umbracoInternalRedirectId"); }
		}

		/// <summary>LinkedIn</summary>
		[ImplementPropertyType("linkedin")]
		public string Linkedin
		{
			get { return this.GetPropertyValue<string>("linkedin"); }
		}

		/// <summary>Open Graph Image</summary>
		[ImplementPropertyType("openGraphImage")]
		public IPublishedContent OpenGraphImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("openGraphImage"); }
		}

		/// <summary>Pinterest</summary>
		[ImplementPropertyType("pinterest")]
		public string Pinterest
		{
			get { return this.GetPropertyValue<string>("pinterest"); }
		}

		/// <summary>Post Code</summary>
		[ImplementPropertyType("postCode")]
		public string PostCode
		{
			get { return this.GetPropertyValue<string>("postCode"); }
		}

		/// <summary>Site Name</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return this.GetPropertyValue<string>("siteName"); }
		}

		/// <summary>Slideshare</summary>
		[ImplementPropertyType("slideshare")]
		public string Slideshare
		{
			get { return this.GetPropertyValue<string>("slideshare"); }
		}

		/// <summary>Telephone</summary>
		[ImplementPropertyType("telephone")]
		public string Telephone
		{
			get { return this.GetPropertyValue<string>("telephone"); }
		}

		/// <summary>Twitter</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}

		/// <summary>Twitter Card Image</summary>
		[ImplementPropertyType("twitterCardImage")]
		public IPublishedContent TwitterCardImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("twitterCardImage"); }
		}

		/// <summary>Vimeo</summary>
		[ImplementPropertyType("vimeo")]
		public string Vimeo
		{
			get { return this.GetPropertyValue<string>("vimeo"); }
		}

		/// <summary>Youtube</summary>
		[ImplementPropertyType("youtube")]
		public string Youtube
		{
			get { return this.GetPropertyValue<string>("youtube"); }
		}
	}
}
